// 초기 제품 데이터나 상품 상세 URL 기준을 맞출 때 참고하는 올리브영 상품 목록입니다.
function oliveYoungProductUrl(goodsNo) {
    return `https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=${goodsNo}`;
}

const OLIVE_YOUNG_PRODUCT_REFERENCES = [
    {
        sourceIngredient: '나이아신아마이드',
        brandName: 'The Ordinary',
        productName: '디오디너리 나이아신아마이드 10% + 징크 1%',
        productType: 'serum',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000158615'),
        productImg: null,
        description: '나이아신아마이드 검색 기준의 대표 세럼 후보입니다.',
        ingredients: ['나이아신아마이드'],
    },
    {
        sourceIngredient: '알부틴',
        brandName: 'The Ordinary',
        productName: '디오디너리 알파 알부틴 2% + HA',
        productType: 'serum',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000227405'),
        productImg: null,
        description: '알부틴 검색 기준의 대표 브라이트닝 세럼 후보입니다.',
        ingredients: ['알부틴'],
    },
    {
        sourceIngredient: '비타민C',
        brandName: 'GOODAL',
        productName: '구달 청귤 비타C 잡티케어 세럼',
        productType: 'serum',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000229789'),
        productImg: null,
        description: '비타민C 검색 기준의 브라이트닝 세럼 후보입니다.',
        ingredients: ['비타민C', '알부틴', '나이아신아마이드'],
    },
    {
        sourceIngredient: '비타민C 유도체',
        brandName: 'Dr.Althea',
        productName: '닥터엘시아 비타민C 부스팅 세럼',
        productType: 'serum',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000221942'),
        productImg: null,
        description: '비타민C 유도체 검색 기준의 톤 케어 세럼 후보입니다.',
        ingredients: ['비타민C 유도체', '비타민C', '나이아신아마이드'],
    },
    {
        sourceIngredient: '트라넥사믹애씨드',
        brandName: 'Torriden',
        productName: '토리든 셀메이징 비타C 브라이트닝 앰플',
        productType: 'ampoule',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000200310'),
        productImg: null,
        description: '트라넥사믹애씨드 검색 기준의 색소침착 케어 앰플 후보입니다.',
        ingredients: ['트라넥사믹애씨드', '비타민C 유도체'],
    },
    {
        sourceIngredient: '감초추출물',
        brandName: 'SKIN1004',
        productName: '스킨1004 마다가스카르 센텔라 앰플',
        productType: 'ampoule',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000161581'),
        productImg: null,
        description: '감초추출물 검색 기준의 진정 보조 앰플 후보입니다.',
        ingredients: ['감초추출물'],
    },
    {
        sourceIngredient: '알파-비사보롤',
        brandName: 'isoi',
        productName: '아이소이 잡티세럼',
        productType: 'serum',
        priceAmount: 0,
        productUrl: null,
        productImg: null,
        description: '알파-비사보롤 검색 기준의 잡티 케어 세럼 후보입니다.',
        ingredients: ['알파-비사보롤', '알부틴'],
    },
    {
        sourceIngredient: '글루타치온',
        brandName: 'numbuzin',
        productName: '넘버즈인 5번 글루타치온C 흔적 앰플',
        productType: 'ampoule',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000189837'),
        productImg: null,
        description: '글루타치온 검색 기준의 브라이트닝 앰플 후보입니다.',
        ingredients: ['글루타치온', '나이아신아마이드', '비타민C 유도체'],
    },
    {
        sourceIngredient: '닥나무추출물',
        brandName: 'HANYUL',
        productName: '한율 어린쑥 수분진정 세럼',
        productType: 'serum',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000233771'),
        productImg: null,
        description: '닥나무추출물 검색 기준의 톤 케어 보조 세럼 후보입니다.',
        ingredients: ['닥나무추출물'],
    },
    {
        sourceIngredient: '아데노신',
        brandName: 'AHC',
        productName: 'AHC 텐 레볼루션 리얼 아이크림 포 페이스',
        productType: 'cream',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000191733'),
        productImg: null,
        description: '아데노신 검색 기준의 주름 케어 크림 후보입니다.',
        ingredients: ['아데노신', '펩타이드'],
    },
    {
        sourceIngredient: '레티놀',
        brandName: 'SOME BY MI',
        productName: '썸바이미 레티놀 인텐스 리액티베이팅 세럼',
        productType: 'serum',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000197985'),
        productImg: null,
        description: '레티놀 검색 기준의 주름 케어 세럼 후보입니다.',
        ingredients: ['레티놀', '바쿠치올', '펩타이드'],
    },
    {
        sourceIngredient: '레티날',
        brandName: 'Beauty of Joseon',
        productName: '조선미녀 맑은쌀 레티날 세럼',
        productType: 'serum',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000224658'),
        productImg: null,
        description: '레티날 검색 기준의 탄력 케어 세럼 후보입니다.',
        ingredients: ['레티날', '나이아신아마이드'],
    },
    {
        sourceIngredient: '바쿠치올',
        brandName: 'SOME BY MI',
        productName: '썸바이미 레티놀 인텐스 리액티베이팅 세럼',
        productType: 'serum',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000197985'),
        productImg: null,
        description: '바쿠치올 검색 기준의 저자극 탄력 세럼 후보입니다.',
        ingredients: ['바쿠치올', '레티놀', '펩타이드'],
    },
    {
        sourceIngredient: '펩타이드',
        brandName: 'BIOHEAL BOH',
        productName: '바이오힐보 프로바이오덤 리프팅 크림',
        productType: 'cream',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000214797'),
        productImg: null,
        description: '펩타이드 검색 기준의 리프팅 크림 후보입니다.',
        ingredients: ['펩타이드', '콜라겐', '엘라스틴'],
    },
    {
        sourceIngredient: '콜라겐',
        brandName: 'MEDIHEAL',
        productName: '메디힐 레티놀 콜라겐 리프팅 패드',
        productType: 'pad',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000189006'),
        productImg: null,
        description: '콜라겐 검색 기준의 탄력 패드 후보입니다.',
        ingredients: ['콜라겐', '레티놀', '펩타이드'],
    },
    {
        sourceIngredient: '엘라스틴',
        brandName: 'BIOHEAL BOH',
        productName: '바이오힐보 프로바이오덤 리프팅 크림',
        productType: 'cream',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000214797'),
        productImg: null,
        description: '엘라스틴 검색 기준의 탄력 크림 후보입니다.',
        ingredients: ['엘라스틴', '펩타이드', '콜라겐'],
    },
    {
        sourceIngredient: '토코페롤',
        brandName: 'COSRX',
        productName: '코스알엑스 더 레티놀 0.1 크림',
        productType: 'cream',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000180543'),
        productImg: null,
        description: '토코페롤 검색 기준의 항산화 보조 크림 후보입니다.',
        ingredients: ['토코페롤', '레티놀'],
    },
    {
        sourceIngredient: '세라마이드',
        brandName: 'Dr.Jart+',
        productName: '닥터자르트 세라마이딘 크림',
        productType: 'cream',
        priceAmount: 0,
        productUrl: oliveYoungProductUrl('A000000209135'),
        productImg: null,
        description: '세라마이드 검색 기준의 장벽 케어 크림 후보입니다.',
        ingredients: ['세라마이드'],
    },
];

module.exports = {
    OLIVE_YOUNG_PRODUCT_REFERENCES,
};
